apiVersion: apps/v1
kind: Deployment
metadata:

  name: merchants-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: merchants-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: merchants-service
    spec:
      containers:
      - image: testsridhar/merchants-service:0.0.1
        imagePullPolicy: Always
        name: merchants-service
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: 400Mi
          requests:
            cpu: 500m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

