apiVersion: v1
kind: Service
metadata:
  name: merchants-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort:  8080
  selector:
    app: merchants-service
  sessionAffinity: None
  type: NodePort
