mongo:
  database: dxun
  merchant_collection: merchant
  merchant_workflow_collection: merchant_workflow

kafka:
  consumer:
    group-id: client_product_service
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


#Spring boot actuator
management:
  server:
    port: 9006