mongo:
  database: dxun
  merchant_collection: merchant
  merchant_workflow_collection: merchant_workflow

kafka:
  consumer:
    group-id: merchant_service
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer


#Spring boot actuator
management:
  server:
    port: 9006