package com.dxunited.merchantservice.controller;

import com.dxunited.merchantservice.adaptor.MerchantAdaptor;
import com.dxunited.merchantservice.connector.MerchantDBConnector;
import com.dxunited.merchantservice.constants.Constants;
import com.dxunited.merchantservice.response.EventResponse;
import com.dxunited.merchantservice.response.GenericResponse;
import com.dxunited.merchantservice.response.MerchantBaseResponse;
import com.dxunited.merchantservice.service.MerchantService;
import com.fasterxml.jackson.core.JsonProcessingException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

@RunWith(MockitoJUnitRunner.class)
public class MerchantControllerTest {

    @Mock
    MerchantService merchantService;
    @Mock
    MerchantBaseResponse merchantBaseResponse;
    @Mock
    MerchantDBConnector merchantDBConnector;
    @Mock
    MerchantAdaptor merchantAdaptor;
    @InjectMocks
    MerchantController merchantController;

    private String token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuRmhiUXdURTZVNk0wc3lsUHFIWVZiWVV2NTFINHBFbEUtNXp2Nlp6T1VnIn0.eyJqdGkiOiJiNWU5Mjg1NS0wY2I4LTRlMDEtOWVkNy03ZTA5ODZmMWNlZTEiLCJleHAiOjE2MzcwOTE0ODYsIm5iZiI6MCwiaWF0IjoxNjM3MDg1NDg2LCJpc3MiOiJodHRwOi8vZWMyLTE4LTE5MS0xOTktMjM3LnVzLWVhc3QtMi5jb21wdXRlLmFtYXpvbmF3cy5jb206ODA4MC9hdXRoL3JlYWxtcy9tYXN0ZXIiLCJhdWQiOlsidGVzdC1yZWFsbSIsInN6ZWxscy1yZWFsbSIsIkNsb2FrRGVtby1yZWFsbSIsIm1hc3Rlci1yZWFsbSIsIm1hdXRpYy1yZWFsbSIsImFjY291bnQiLCJNYXV0aWMgVHJhc2gtcmVhbG0iXSwic3ViIjoiMjZmZmRmNzItMmFlYS00NjVlLTkzYWQtZmQ2M2FlZTQ0YWIwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic3plbGxzLXNlcnZlciIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6Ijk1ZDBiZmEzLWVlZGYtNDU5ZS04MjVjLTc4OTExMzIyYjdkZCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJjcmVhdGUtcmVhbG0iLCJvZmZsaW5lX2FjY2VzcyIsImFkbWluIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJzemVsbHMtc2VydmVyIjp7InJvbGVzIjpbInVtYV9wcm90ZWN0aW9uIl19LCJ0ZXN0LXJlYWxtIjp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJzemVsbHMtcmVhbG0iOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sIkNsb2FrRGVtby1yZWFsbSI6eyJyb2xlcyI6WyJ2aWV3LWlkZW50aXR5LXByb3ZpZGVycyIsInZpZXctcmVhbG0iLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwibWFzdGVyLXJlYWxtIjp7InJvbGVzIjpbInZpZXctcmVhbG0iLCJ2aWV3LWlkZW50aXR5LXByb3ZpZGVycyIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJtYXV0aWMtcmVhbG0iOnsicm9sZXMiOlsidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJ2aWV3LXJlYWxtIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfSwiTWF1dGljIFRyYXNoLXJlYWxtIjp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJ1c2VyX2lkIjoiMjZmZmRmNzItMmFlYS00NjVlLTkzYWQtZmQ2M2FlZTQ0YWIwIiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VsdmFnYW5wcm9maWxlMUBnbWFpbC5jb20ifQ.BcIc0fbsLPKYdOy_inNUdgpF-StQ6Obtu-g23vc6_NC0INpKTwe5Uh3QIJSbmiguVi6LenbXrC1y5QojKNTMpZo2l6wn9zSunYiIAsbTRJAbOWwso1lF_PKWA9l89EgEQn2jGnblDmBnAp4T52PzaPfwZrKogMvwpggX7CqBPSmKcEoXyAl7_jwb9w-6Ut3oK4zTjLaksfX97KR2Y0T8XJWc1NQ6yKrJle8OIoVZE68R2YLxNWMf-kuzLaRjZusrumkDDQMkg1dClw4yqiJqRefpcP_YGbPzx151nkQOD0ir7mqkYMEUEzS2s-QFHc0RHD38iwkveTOQKcQgEV9KAg";

    @Test
    public void create() throws JsonProcessingException {
        String merchantString = "{\n" +
                "    \"externalMerchantId\": \"3\",\n" +
                "    \"MerchantId\": \"3\",\n" +
                "    \"type\": \"string\",\n" +
                "}";
        EventResponse response = new EventResponse();
        GenericResponse genericResponse = GenericResponse.builder().data(response).message("Merchant Created").build();
        Mockito.when(merchantService.createMerchantEvent(Constants.CREATE_MERCHANT, merchantString)).thenReturn(response);
        Assert.assertEquals(merchantController.createMerchant(token, "1111", merchantString),
                new ResponseEntity<>(genericResponse, HttpStatus.OK));
    }
}
